services:
  db:
    image: postgres:17
    container_name: fishingStore-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: fishingStore
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Password123
    ports:
      - "5555:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: