spring.application.name=FishingStore
spring.datasource.url=jdbc:postgresql://localhost:5555/fishingStore
spring.datasource.username=postgres
spring.datasource.password=Password123

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=PT15M
jwt.refresh-expiration=P7D

app.admin.first-name=Admin
app.admin.last-name=Admin
app.admin.email=admin@fishingstore.com
app.admin.username=admin
app.admin.password=Passw0rd
app.base-url=http://localhost:8080
app.upload.dir=uploads
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB


paypal.client-id=AfVsg0bJyrjkjM9zGUyJYT-XghXzRocUmdhy56EfbFAbnBpoec4X7qicQ2caxbzpHmiNw9OmrsfoC2tB
paypal.client-secret=EM4Hrnp-K0jrC8n4Mzq649CLFzexvCypm74euqWtzK08Xz4DlQrX1wcLSu8T_BtRziIcXieKTWWrnvbF
paypal.base-url=https://api-m.sandbox.paypal.com
