spring.application.name=FishingStore

spring.datasource.url=jdbc:postgresql://localhost:5555/fishingStore
spring.datasource.username=postgres
spring.datasource.password=Password123

#automatski kreira i mjenja tablice temeljem entity klasa
spring.jpa.hibernate.ddl-auto=update

#prikazuje SQL upite u konzoli
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

jwt.expiration=15m
jwt.refresh-expiration=7d